%marker @var

%header {
TEST HEADER $$         " $$         " /* $$         */ // $$
TEST HEADER $0         " $0         " /* $0         */ // $0
TEST HEADER $0s        " $0s        " /* $0s        */ // $0s
TEST HEADER $0e        " $0e        " /* $0e        */ // $0e
TEST HEADER $123       " $123       " /* $123       */ // $123
TEST HEADER $123s      " $123s      " /* $123s      */ // $123s
TEST HEADER $123e      " $123e      " /* $123e      */ // $123e
TEST HEADER ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST HEADER ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST HEADER ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST HEADER \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST HEADER \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST HEADER @@                     " @@                     " /* @@                     */ // @@
TEST HEADER @var                   " @var                   " /* @var                   */ // @var
TEST HEADER @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST HEADER @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST HEADER @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST HEADER @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST HEADER @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST HEADER @baz                   " @baz                   " /* @baz                   */ // @baz
TEST HEADER @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST HEADER @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST HEADER @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST HEADER @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST HEADER @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST HEADER \@var                  " \@var                  " /* \@var                  */ // \@var
TEST HEADER \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST HEADER \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST HEADER \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST HEADER \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST HEADER \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%source {
TEST SOURCE $$         " $$         " /* $$         */ // $$
TEST SOURCE $0         " $0         " /* $0         */ // $0
TEST SOURCE $0s        " $0s        " /* $0s        */ // $0s
TEST SOURCE $0e        " $0e        " /* $0e        */ // $0e
TEST SOURCE $123       " $123       " /* $123       */ // $123
TEST SOURCE $123s      " $123s      " /* $123s      */ // $123s
TEST SOURCE $123e      " $123e      " /* $123e      */ // $123e
TEST SOURCE ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST SOURCE ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST SOURCE ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST SOURCE \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST SOURCE \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST SOURCE @@                     " @@                     " /* @@                     */ // @@
TEST SOURCE @var                   " @var                   " /* @var                   */ // @var
TEST SOURCE @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST SOURCE @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST SOURCE @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST SOURCE @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST SOURCE @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST SOURCE @baz                   " @baz                   " /* @baz                   */ // @baz
TEST SOURCE @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST SOURCE @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST SOURCE @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST SOURCE @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST SOURCE @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST SOURCE \@var                  " \@var                  " /* \@var                  */ // \@var
TEST SOURCE \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST SOURCE \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST SOURCE \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST SOURCE \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST SOURCE \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%common {
TEST COMMON $$         " $$         " /* $$         */ // $$
TEST COMMON $0         " $0         " /* $0         */ // $0
TEST COMMON $0s        " $0s        " /* $0s        */ // $0s
TEST COMMON $0e        " $0e        " /* $0e        */ // $0e
TEST COMMON $123       " $123       " /* $123       */ // $123
TEST COMMON $123s      " $123s      " /* $123s      */ // $123s
TEST COMMON $123e      " $123e      " /* $123e      */ // $123e
TEST COMMON ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST COMMON ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST COMMON ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST COMMON \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST COMMON \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST COMMON @@                     " @@                     " /* @@                     */ // @@
TEST COMMON @var                   " @var                   " /* @var                   */ // @var
TEST COMMON @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST COMMON @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST COMMON @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST COMMON @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST COMMON @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST COMMON @baz                   " @baz                   " /* @baz                   */ // @baz
TEST COMMON @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST COMMON @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST COMMON @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST COMMON @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST COMMON @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST COMMON \@var                  " \@var                  " /* \@var                  */ // \@var
TEST COMMON \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST COMMON \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST COMMON \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST COMMON \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST COMMON \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%earlyheader {
TEST EARLYHEADER $$         " $$         " /* $$         */ // $$
TEST EARLYHEADER $0         " $0         " /* $0         */ // $0
TEST EARLYHEADER $0s        " $0s        " /* $0s        */ // $0s
TEST EARLYHEADER $0e        " $0e        " /* $0e        */ // $0e
TEST EARLYHEADER $123       " $123       " /* $123       */ // $123
TEST EARLYHEADER $123s      " $123s      " /* $123s      */ // $123s
TEST EARLYHEADER $123e      " $123e      " /* $123e      */ // $123e
TEST EARLYHEADER ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST EARLYHEADER ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST EARLYHEADER ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST EARLYHEADER \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST EARLYHEADER \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST EARLYHEADER @@                     " @@                     " /* @@                     */ // @@
TEST EARLYHEADER @var                   " @var                   " /* @var                   */ // @var
TEST EARLYHEADER @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST EARLYHEADER @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST EARLYHEADER @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST EARLYHEADER @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST EARLYHEADER @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST EARLYHEADER @baz                   " @baz                   " /* @baz                   */ // @baz
TEST EARLYHEADER @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST EARLYHEADER @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST EARLYHEADER @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST EARLYHEADER @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST EARLYHEADER @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST EARLYHEADER \@var                  " \@var                  " /* \@var                  */ // \@var
TEST EARLYHEADER \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST EARLYHEADER \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST EARLYHEADER \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST EARLYHEADER \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST EARLYHEADER \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%earlysource {
TEST EARLYSOURCE $$         " $$         " /* $$         */ // $$
TEST EARLYSOURCE $0         " $0         " /* $0         */ // $0
TEST EARLYSOURCE $0s        " $0s        " /* $0s        */ // $0s
TEST EARLYSOURCE $0e        " $0e        " /* $0e        */ // $0e
TEST EARLYSOURCE $123       " $123       " /* $123       */ // $123
TEST EARLYSOURCE $123s      " $123s      " /* $123s      */ // $123s
TEST EARLYSOURCE $123e      " $123e      " /* $123e      */ // $123e
TEST EARLYSOURCE ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST EARLYSOURCE ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST EARLYSOURCE ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST EARLYSOURCE \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST EARLYSOURCE \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST EARLYSOURCE @@                     " @@                     " /* @@                     */ // @@
TEST EARLYSOURCE @var                   " @var                   " /* @var                   */ // @var
TEST EARLYSOURCE @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST EARLYSOURCE @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST EARLYSOURCE @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST EARLYSOURCE @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST EARLYSOURCE @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST EARLYSOURCE @baz                   " @baz                   " /* @baz                   */ // @baz
TEST EARLYSOURCE @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST EARLYSOURCE @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST EARLYSOURCE @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST EARLYSOURCE @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST EARLYSOURCE @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST EARLYSOURCE \@var                  " \@var                  " /* \@var                  */ // \@var
TEST EARLYSOURCE \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST EARLYSOURCE \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST EARLYSOURCE \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST EARLYSOURCE \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST EARLYSOURCE \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%earlycommon {
TEST EARLYCOMMON $$         " $$         " /* $$         */ // $$
TEST EARLYCOMMON $0         " $0         " /* $0         */ // $0
TEST EARLYCOMMON $0s        " $0s        " /* $0s        */ // $0s
TEST EARLYCOMMON $0e        " $0e        " /* $0e        */ // $0e
TEST EARLYCOMMON $123       " $123       " /* $123       */ // $123
TEST EARLYCOMMON $123s      " $123s      " /* $123s      */ // $123s
TEST EARLYCOMMON $123e      " $123e      " /* $123e      */ // $123e
TEST EARLYCOMMON ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST EARLYCOMMON ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST EARLYCOMMON ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST EARLYCOMMON \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST EARLYCOMMON \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST EARLYCOMMON @@                     " @@                     " /* @@                     */ // @@
TEST EARLYCOMMON @var                   " @var                   " /* @var                   */ // @var
TEST EARLYCOMMON @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST EARLYCOMMON @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST EARLYCOMMON @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST EARLYCOMMON @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST EARLYCOMMON @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST EARLYCOMMON @baz                   " @baz                   " /* @baz                   */ // @baz
TEST EARLYCOMMON @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST EARLYCOMMON @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST EARLYCOMMON @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST EARLYCOMMON @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST EARLYCOMMON @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST EARLYCOMMON \@var                  " \@var                  " /* \@var                  */ // \@var
TEST EARLYCOMMON \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST EARLYCOMMON \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST EARLYCOMMON \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST EARLYCOMMON \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST EARLYCOMMON \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
}

%value "double"

%auxil "long"

%prefix "foo1"

FILE
   <- '_'
    &{
        TEST PROGPRED0 $$.        " $$.        " /* $$.        */ // $$.
        TEST PROGPRED0 $$$        " $$$        " /* $$$        */ // $$$
        TEST PROGPRED0 $$0        " $$0        " /* $$0        */ // $$0
        TEST PROGPRED0 $0.        " $0.        " /* $0.        */ // $0.
        TEST PROGPRED0 $0$        " $0$        " /* $0$        */ // $0$
        TEST PROGPRED0 $01        " $01        " /* $01        */ // $01
        TEST PROGPRED0 $0s.       " $0s.       " /* $0s.       */ // $0s.
        TEST PROGPRED0 $0s$       " $0s$       " /* $0s$       */ // $0s$
        TEST PROGPRED0 $0s1       " $0s1       " /* $0s1       */ // $0s1
        TEST PROGPRED0 $01s       " $01s       " /* $01s       */ // $01s
        TEST PROGPRED0 $0e.       " $0e.       " /* $0e.       */ // $0e.
        TEST PROGPRED0 $0e$       " $0e$       " /* $0e$       */ // $0e$
        TEST PROGPRED0 $0e1       " $0e1       " /* $0e1       */ // $0e1
        TEST PROGPRED0 $01e       " $01e       " /* $01e       */ // $01e
        TEST PROGPRED0 $1.        " $1.        " /* $1.        */ // $1.
        TEST PROGPRED0 $1$        " $1$        " /* $1$        */ // $1$
        TEST PROGPRED0 $1s.       " $1s.       " /* $1s.       */ // $1s.
        TEST PROGPRED0 $1s$       " $1s$       " /* $1s$       */ // $1s$
        TEST PROGPRED0 $1s1       " $1s1       " /* $1s1       */ // $1s1
        TEST PROGPRED0 $1e.       " $1e.       " /* $1e.       */ // $1e.
        TEST PROGPRED0 $1e$       " $1e$       " /* $1e$       */ // $1e$
        TEST PROGPRED0 $1e1       " $1e1       " /* $1e1       */ // $1e1
        TEST PROGPRED0 $2.        " $2.        " /* $2.        */ // $2.
        TEST PROGPRED0 $2$        " $2$        " /* $2$        */ // $2$
        TEST PROGPRED0 $2s.       " $2s.       " /* $2s.       */ // $2s.
        TEST PROGPRED0 $2s$       " $2s$       " /* $2s$       */ // $2s$
        TEST PROGPRED0 $2s1       " $2s1       " /* $2s1       */ // $2s1
        TEST PROGPRED0 $2e.       " $2e.       " /* $2e.       */ // $2e.
        TEST PROGPRED0 $2e$       " $2e$       " /* $2e$       */ // $2e$
        TEST PROGPRED0 $2e1       " $2e1       " /* $2e1       */ // $2e1
        TEST PROGPRED0 $123.      " $123.      " /* $123.      */ // $123.
        TEST PROGPRED0 $123$      " $123$      " /* $123$      */ // $123$
        TEST PROGPRED0 $123_      " $123_      " /* $123_      */ // $123_
        TEST PROGPRED0 $123s.     " $123s.     " /* $123s.     */ // $123s.
        TEST PROGPRED0 $123s$     " $123s$     " /* $123s$     */ // $123s$
        TEST PROGPRED0 $123s_     " $123s_     " /* $123s_     */ // $123s_
        TEST PROGPRED0 $123e.     " $123e.     " /* $123e.     */ // $123e.
        TEST PROGPRED0 $123e$     " $123e$     " /* $123e$     */ // $123e$
        TEST PROGPRED0 $123e_     " $123e_     " /* $123e_     */ // $123e_
        TEST PROGPRED0 ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
        TEST PROGPRED0 ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
        TEST PROGPRED0 ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
        TEST PROGPRED0 \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
        TEST PROGPRED0 \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
        TEST PROGPRED0 @@                      " @@                      " /* @@                      */ // @@
        TEST PROGPRED0 @@@                     " @@@                     " /* @@@                     */ // @@@
        TEST PROGPRED0 @@var                   " @@var                   " /* @@var                   */ // @@var
        TEST PROGPRED0 @var                    " @var                    " /* @var                    */ // @var
        TEST PROGPRED0 @var.                   " @var.                   " /* @var.                   */ // @var.
        TEST PROGPRED0 @var@                   " @var@                   " /* @var@                   */ // @var@
        TEST PROGPRED0 @var1                   " @var1                   " /* @var1                   */ // @var1
        TEST PROGPRED0 @var.get_string()       " @var.get_string()       " /* @var.get_string()       */ // @var.get_string()
        TEST PROGPRED0 @var.set_string($0)     " @var.set_string($0)     " /* @var.set_string($0)     */ // @var.set_string($0)
        TEST PROGPRED0 @var.append_string($0)  " @var.append_string($0)  " /* @var.append_string($0)  */ // @var.append_string($0)
        TEST PROGPRED0 @var.save()             " @var.save()             " /* @var.save()             */ // @var.save()
        TEST PROGPRED0 @var.restore()          " @var.restore()          " /* @var.restore()          */ // @var.restore()
        TEST PROGPRED0 @baz                    " @baz                    " /* @baz                    */ // @baz
        TEST PROGPRED0 @baz.get_string()       " @baz.get_string()       " /* @baz.get_string()       */ // @baz.get_string()
        TEST PROGPRED0 @baz.set_string($0)     " @baz.set_string($0)     " /* @baz.set_string($0)     */ // @baz.set_string($0)
        TEST PROGPRED0 @baz.append_string($0)  " @baz.append_string($0)  " /* @baz.append_string($0)  */ // @baz.append_string($0)
        TEST PROGPRED0 @baz.save()             " @baz.save()             " /* @baz.save()             */ // @baz.save()
        TEST PROGPRED0 @baz.restore()          " @baz.restore()          " /* @baz.restore()          */ // @baz.restore()
        TEST PROGPRED0 \@var                   " \@var                   " /* \@var                   */ // \@var
        TEST PROGPRED0 \@var.get_string()      " \@var.get_string()      " /* \@var.get_string()      */ // \@var.get_string()
        TEST PROGPRED0 \@var.set_string($0)    " \@var.set_string($0)    " /* \@var.set_string($0)    */ // \@var.set_string($0)
        TEST PROGPRED0 \@var.append_string($0) " \@var.append_string($0) " /* \@var.append_string($0) */ // \@var.append_string($0)
        TEST PROGPRED0 \@var.save()            " \@var.save()            " /* \@var.save()            */ // \@var.save()
        TEST PROGPRED0 \@var.restore()         " \@var.restore()         " /* \@var.restore()         */ // \@var.restore()
        }
    < "..." >
    {
        TEST ACTION0 $$.        " $$.        " /* $$.        */ // $$.
        TEST ACTION0 $$$        " $$$        " /* $$$        */ // $$$
        TEST ACTION0 $$0        " $$0        " /* $$0        */ // $$0
        TEST ACTION0 $0.        " $0.        " /* $0.        */ // $0.
        TEST ACTION0 $0$        " $0$        " /* $0$        */ // $0$
        TEST ACTION0 $01        " $01        " /* $01        */ // $01
        TEST ACTION0 $0s.       " $0s.       " /* $0s.       */ // $0s.
        TEST ACTION0 $0s$       " $0s$       " /* $0s$       */ // $0s$
        TEST ACTION0 $0s1       " $0s1       " /* $0s1       */ // $0s1
        TEST ACTION0 $01s       " $01s       " /* $01s       */ // $01s
        TEST ACTION0 $0e.       " $0e.       " /* $0e.       */ // $0e.
        TEST ACTION0 $0e$       " $0e$       " /* $0e$       */ // $0e$
        TEST ACTION0 $0e1       " $0e1       " /* $0e1       */ // $0e1
        TEST ACTION0 $01e       " $01e       " /* $01e       */ // $01e
        TEST ACTION0 $1.        " $1.        " /* $1.        */ // $1.
        TEST ACTION0 $1$        " $1$        " /* $1$        */ // $1$
        TEST ACTION0 $1s.       " $1s.       " /* $1s.       */ // $1s.
        TEST ACTION0 $1s$       " $1s$       " /* $1s$       */ // $1s$
        TEST ACTION0 $1s1       " $1s1       " /* $1s1       */ // $1s1
        TEST ACTION0 $1e.       " $1e.       " /* $1e.       */ // $1e.
        TEST ACTION0 $1e$       " $1e$       " /* $1e$       */ // $1e$
        TEST ACTION0 $1e1       " $1e1       " /* $1e1       */ // $1e1
        TEST ACTION0 $2.        " $2.        " /* $2.        */ // $2.
        TEST ACTION0 $2$        " $2$        " /* $2$        */ // $2$
        TEST ACTION0 $2s.       " $2s.       " /* $2s.       */ // $2s.
        TEST ACTION0 $2s$       " $2s$       " /* $2s$       */ // $2s$
        TEST ACTION0 $2s1       " $2s1       " /* $2s1       */ // $2s1
        TEST ACTION0 $2e.       " $2e.       " /* $2e.       */ // $2e.
        TEST ACTION0 $2e$       " $2e$       " /* $2e$       */ // $2e$
        TEST ACTION0 $2e1       " $2e1       " /* $2e1       */ // $2e1
        TEST ACTION0 $123.      " $123.      " /* $123.      */ // $123.
        TEST ACTION0 $123$      " $123$      " /* $123$      */ // $123$
        TEST ACTION0 $123_      " $123_      " /* $123_      */ // $123_
        TEST ACTION0 $123s.     " $123s.     " /* $123s.     */ // $123s.
        TEST ACTION0 $123s$     " $123s$     " /* $123s$     */ // $123s$
        TEST ACTION0 $123s_     " $123s_     " /* $123s_     */ // $123s_
        TEST ACTION0 $123e.     " $123e.     " /* $123e.     */ // $123e.
        TEST ACTION0 $123e$     " $123e$     " /* $123e$     */ // $123e$
        TEST ACTION0 $123e_     " $123e_     " /* $123e_     */ // $123e_
        TEST ACTION0 ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
        TEST ACTION0 ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
        TEST ACTION0 ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
        TEST ACTION0 \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
        TEST ACTION0 \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
        TEST ACTION0 @@                      " @@                      " /* @@                      */ // @@
        TEST ACTION0 @@@                     " @@@                     " /* @@@                     */ // @@@
        TEST ACTION0 @@var                   " @@var                   " /* @@var                   */ // @@var
        TEST ACTION0 @var                    " @var                    " /* @var                    */ // @var
        TEST ACTION0 @var.                   " @var.                   " /* @var.                   */ // @var.
        TEST ACTION0 @var@                   " @var@                   " /* @var@                   */ // @var@
        TEST ACTION0 @var1                   " @var1                   " /* @var1                   */ // @var1
        TEST ACTION0 @var.get_string()       " @var.get_string()       " /* @var.get_string()       */ // @var.get_string()
        TEST ACTION0 @var.set_string($0)     " @var.set_string($0)     " /* @var.set_string($0)     */ // @var.set_string($0)
        TEST ACTION0 @var.append_string($0)  " @var.append_string($0)  " /* @var.append_string($0)  */ // @var.append_string($0)
        TEST ACTION0 @var.save()             " @var.save()             " /* @var.save()             */ // @var.save()
        TEST ACTION0 @var.restore()          " @var.restore()          " /* @var.restore()          */ // @var.restore()
        TEST ACTION0 @baz                    " @baz                    " /* @baz                    */ // @baz
        TEST ACTION0 @baz.get_string()       " @baz.get_string()       " /* @baz.get_string()       */ // @baz.get_string()
        TEST ACTION0 @baz.set_string($0)     " @baz.set_string($0)     " /* @baz.set_string($0)     */ // @baz.set_string($0)
        TEST ACTION0 @baz.append_string($0)  " @baz.append_string($0)  " /* @baz.append_string($0)  */ // @baz.append_string($0)
        TEST ACTION0 @baz.save()             " @baz.save()             " /* @baz.save()             */ // @baz.save()
        TEST ACTION0 @baz.restore()          " @baz.restore()          " /* @baz.restore()          */ // @baz.restore()
        TEST ACTION0 \@var                   " \@var                   " /* \@var                   */ // \@var
        TEST ACTION0 \@var.get_string()      " \@var.get_string()      " /* \@var.get_string()      */ // \@var.get_string()
        TEST ACTION0 \@var.set_string($0)    " \@var.set_string($0)    " /* \@var.set_string($0)    */ // \@var.set_string($0)
        TEST ACTION0 \@var.append_string($0) " \@var.append_string($0) " /* \@var.append_string($0) */ // \@var.append_string($0)
        TEST ACTION0 \@var.save()            " \@var.save()            " /* \@var.save()            */ // \@var.save()
        TEST ACTION0 \@var.restore()         " \@var.restore()         " /* \@var.restore()         */ // \@var.restore()
        }
    / '$'    &{ TEST PROGPRED1 $$    " $$    " /* $$    */ } { TEST ACTION1 $$    " $$    " /* $$    */ }
    / '0'    &{ TEST PROGPRED2 $0    " $0    " /* $0    */ } { TEST ACTION2 $0    " $0    " /* $0    */ }
    / '0s'   &{ TEST PROGPRED3 $0s   " $0s   " /* $0s   */ } { TEST ACTION3 $0s   " $0s   " /* $0s   */ }
    / '0e'   &{ TEST PROGPRED4 $0e   " $0e   " /* $0e   */ } { TEST ACTION4 $0e   " $0e   " /* $0e   */ }
    / '123'  &{ TEST PROGPRED5 $123  " $123  " /* $123  */ } { TEST ACTION5 $123  " $123  " /* $123  */ }
    / '123s' &{ TEST PROGPRED6 $123s " $123s " /* $123s */ } { TEST ACTION6 $123s " $123s " /* $123s */ }
    / '123e' &{ TEST PROGPRED7 $123e " $123e " /* $123e */ } { TEST ACTION7 $123e " $123e " /* $123e */ }

%%

TEST FOOTER $$         " $$         " /* $$         */ // $$
TEST FOOTER $0         " $0         " /* $0         */ // $0
TEST FOOTER $0s        " $0s        " /* $0s        */ // $0s
TEST FOOTER $0e        " $0e        " /* $0e        */ // $0e
TEST FOOTER $123       " $123       " /* $123       */ // $123
TEST FOOTER $123s      " $123s      " /* $123s      */ // $123s
TEST FOOTER $123e      " $123e      " /* $123e      */ // $123e
TEST FOOTER ${prefix}  " ${prefix}  " /* ${prefix}  */ // ${prefix}
TEST FOOTER ${PREFIX}  " ${PREFIX}  " /* ${PREFIX}  */ // ${PREFIX}
TEST FOOTER ${bar}     " ${bar}     " /* ${bar}     */ // ${bar}
TEST FOOTER \${prefix} " \${prefix} " /* \${prefix} */ // \${prefix}
TEST FOOTER \${PREFIX} " \${PREFIX} " /* \${PREFIX} */ // \${PREFIX}
TEST FOOTER @@                     " @@                     " /* @@                     */ // @@
TEST FOOTER @var                   " @var                   " /* @var                   */ // @var
TEST FOOTER @var.get_string()      " @var.get_string()      " /* @var.get_string()      */ // @var.get_string()
TEST FOOTER @var.set_string($0)    " @var.set_string($0)    " /* @var.set_string($0)    */ // @var.set_string($0)
TEST FOOTER @var.append_string($0) " @var.append_string($0) " /* @var.append_string($0) */ // @var.append_string($0)
TEST FOOTER @var.save()            " @var.save()            " /* @var.save()            */ // @var.save()
TEST FOOTER @var.restore()         " @var.restore()         " /* @var.restore()         */ // @var.restore()
TEST FOOTER @baz                   " @baz                   " /* @baz                   */ // @baz
TEST FOOTER @baz.get_string()      " @baz.get_string()      " /* @baz.get_string()      */ // @baz.get_string()
TEST FOOTER @baz.set_string($0)    " @baz.set_string($0)    " /* @baz.set_string($0)    */ // @baz.set_string($0)
TEST FOOTER @baz.append_string($0) " @baz.append_string($0) " /* @baz.append_string($0) */ // @baz.append_string($0)
TEST FOOTER @baz.save()            " @baz.save()            " /* @baz.save()            */ // @baz.save()
TEST FOOTER @baz.restore()         " @baz.restore()         " /* @baz.restore()         */ // @baz.restore()
TEST FOOTER \@var                  " \@var                  " /* \@var                  */ // \@var
TEST FOOTER \@var.get_string()     " \@var.get_string()     " /* \@var.get_string()     */ // \@var.get_string()
TEST FOOTER \@var.set_string($0)   " \@var.set_string($0)   " /* \@var.set_string($0)   */ // \@var.set_string($0)
TEST FOOTER \@var.append_string($0)" \@var.append_string($0)" /* \@var.append_string($0)*/ // \@var.append_string($0)
TEST FOOTER \@var.save()           " \@var.save()           " /* \@var.save()           */ // \@var.save()
TEST FOOTER \@var.restore()        " \@var.restore()        " /* \@var.restore()        */ // \@var.restore()
