%header {
TEST [1] HEADER ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] HEADER \${version} " \${version} " /* \${version} */ // \${version}
}

%source {
TEST [1] SOURCE ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] SOURCE \${version} " \${version} " /* \${version} */ // \${version}
}

%common {
TEST [1] COMMON ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] COMMON \${version} " \${version} " /* \${version} */ // \${version}
}

%earlyheader {
TEST [1] EARLYHEADER ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] EARLYHEADER \${version} " \${version} " /* \${version} */ // \${version}
}

%earlysource {
TEST [1] EARLYSOURCE ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] EARLYSOURCE \${version} " \${version} " /* \${version} */ // \${version}
}

%earlycommon {
TEST [1] EARLYCOMMON ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] EARLYCOMMON \${version} " \${version} " /* \${version} */ // \${version}
}

FILE_1
   <- '_'
    &{
        TEST [1] PROGPRED0 ${version}  " ${version}  " /* ${version}  */ // ${version}
        TEST [1] PROGPRED0 \${version} " \${version} " /* \${version} */ // \${version}
    }
    < "..." >
    {
        TEST [1] ACTION0 ${version}  " ${version}  " /* ${version}  */ // ${version}
        TEST [1] ACTION0 \${version} " \${version} " /* \${version} */ // \${version}
    }

%version 543.21.0

%%

TEST [1] FOOTER ${version}  " ${version}  " /* ${version}  */ // ${version}
TEST [1] FOOTER \${version} " \${version} " /* \${version} */ // \${version}
