FILE <- 'test0' _ TOKEN1 (_ TOKEN1)* _*
            /  'test1' _ TOKEN (_ TOKEN)* _*

TOKEN <- CLASS0 / CLASS1 / CLASS2 / CLASS3 / CLASS4 / CLASS5
CLASS0 <- [\^a-z-] { printf("CLASS0: '%s'\n", $0); }
CLASS1 <- [\\\]]   { printf("CLASS1: '%s'\n", $0); }
CLASS2 <- [-あ-ん] { printf("CLASS2: '%s'\n", $0); }
CLASS3 <- [𝓪-𝔃-]   { printf("CLASS3: '%s'\n", $0); }
CLASS4 <- [^0-9]   { printf("CLASS4: '%s'\n", $0); }
CLASS5 <- [^]      { printf("CLASS5: '%s'\n", $0); }

TOKEN1 <- CLASS10 / CLASS11 / CLASS12 / CLASS13
CLASS10 <- 'a'[-+] { printf("CLASS10: '%s'\n", $0); }
CLASS11 <- 'b'[+-]   { printf("CLASS11: '%s'\n", $0); }
CLASS12 <- 'c'[^-+] { printf("CLASS12: '%s'\n", $0); }
CLASS13 <- 'd'[^+-]   { printf("CLASS13: '%s'\n", $0); }

_ <- ' ' / '\n'
